name: lemmy_api_client
version: 0.21.0
homepage: https://github.com/LemmurOrg/lemmy_api_client
description: Future-based http client for the Lemmy API. Provides an easy interface and statically typed responses.

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  json_annotation: ^4.6.0
  http: ^1.0.0
  freezed_annotation: ^2.4.4
  web_socket_channel: ^2.0.0

dev_dependencies:
  build_runner: ^2.4.6
  freezed: ^2.4.2
  json_serializable: ^6.7.1
  test: ^1.24.6
